### ISSUE TITLE
Mana bu yerda reklamaning banneri bo'lishi kerak edi banner yo'q ekan

### ISSUE THREAD

**Issue by Azizbek-Kalandarov** [Usmonkul/Namanganliklar24#4]
![image](https://user-images.githubusercontent.com/74859443/135217088-64649bff-7848-41e6-80e1-515868a52d2e.png)
![image](https://user-images.githubusercontent.com/74859443/135217093-635681b8-41e5-4ae5-b536-24025c1d3a12.png)

**Comment by Usmonkul** [comment]
Fixed
